application: hobby-selector
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /img
  static_dir: images

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /.*
  script: landing.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest